version: '3.8'

services:
  # Serviço do MongoDB
  mongodb:
    image: mongo:latest
    container_name: dynadok-mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: dynadok-test
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Serviço da API NestJS
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dynadok-api
    restart: always
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://root:example@mongodb:27017/dynadok-test?authSource=admin
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TTL: 3600
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local
  redis_data:

networks:
  app-network:
    driver: bridge
